import { describe, expect, it } from 'vitest'

import { site } from '../src/data/site.ts'
import { DARK_QUERY, THEME_STORAGE_KEY } from '../src/theme.ts'
import { themeScript, themeScriptBody } from '../vite/theme-script.ts'

/*
 * Pins the one piece of behaviour that cannot live in a component: the theme
 * has to be on <html> before the first paint. src/main.tsx is loaded as a
 * module script and module scripts are deferred, so the browser is free to
 * paint the parsed document — white, since the light palette is the CSS
 * default and `dark` is only ever added by JS — before the bundle runs.
 * Applying the theme from the bundle alone therefore flashes the light
 * palette at every visitor who stored `dark`, for as long as the bundle
 * takes to arrive. The fix is a render-blocking inline script in <head>,
 * generated by this module from src/theme.ts's and src/data/site.ts's actual
 * exports rather than hand-retyped in index.html, so a change to either
 * source can't silently drift from what the script does.
 */

const body = themeScriptBody()

describe('themeScriptBody', () => {
  it('reads the same storage key as theme.ts', () => {
    expect(body).toContain(THEME_STORAGE_KEY)
  })

  it('falls back to the same media query as theme.ts', () => {
    expect(body).toContain(DARK_QUERY)
  })

  it('sets the same dark theme-color literal as site.ts', () => {
    expect(body).toContain(site.themeColorDark)
    // Light needs no write: it is what the parsed tag already carries. A
    // literal light value inside the script would mean the two disagree
    // about which one is the default.
    expect(body).not.toContain(site.themeColorLight)
  })

  it('sets theme-color in the branch that applies the dark class', () => {
    const classAt = body.indexOf("classList.add('dark')")
    const colorAt = body.indexOf(site.themeColorDark)

    expect(classAt).toBeGreaterThan(-1)
    expect(colorAt).toBeGreaterThan(classAt)
    // No block has closed in between, so the write is still inside the `if`
    // that added the class rather than after it.
    expect(body.slice(classAt, colorAt)).not.toContain('}')
  })

  it('applies the dark class only, and only for dark', () => {
    expect(body).toMatch(/classList\.add\('dark'\)/)
    expect(body).toContain("'dark'")
    expect(body).toContain("'light'")
  })

  it('tolerates localStorage throwing', () => {
    // Safari in private mode throws on the property access itself, and a
    // theme lookup must never be why the page fails to render. Matches
    // getStoredTheme()'s own try/catch.
    expect(body).toMatch(/try\s*\{[\s\S]*catch/)
  })
})

describe('themeScript plugin', () => {
  it('injects a render-blocking script into <head>', async () => {
    const plugin = themeScript()
    const hook = plugin.transformIndexHtml
    const handler = (
      typeof hook === 'function' ? hook : (hook as { handler: unknown }).handler
    ) as () => unknown
    const result = (await handler()) as Array<{
      tag: string
      injectTo: string
      children: string
    }>

    expect(result).toHaveLength(1)
    const [tag] = result
    expect(tag?.tag).toBe('script')
    expect(tag?.injectTo).toBe('head')
    // A theme applied after the document is painted is a flash, not a theme:
    // this script must block rendering, so no `type=module`, `defer` or
    // `async` — this descriptor carries no attrs at all, which renders as a
    // bare <script>.
    expect(tag).not.toHaveProperty('attrs')
    expect(tag?.children).toBe(body)
  })

  it('runs ahead of Vite\'s own build-html plugin', () => {
    // `order: 'pre'` is what keeps this tag ahead of the bundled
    // `<script type="module">` tag Vite injects during `vite build`; without
    // it the build (unlike dev) would place the app bundle tag first.
    const plugin = themeScript()
    const hook = plugin.transformIndexHtml as { order?: string }
    expect(hook.order).toBe('pre')
  })
})
